USE DATABASE DEMODATABASE;

//WHEN GIVING PERMISSION TO PUBLIC,THEY CAN ABLE TO VIEW IT BUT UNABLE TO EDIT OR DELETE

GRANT SELECT ON EDUCATION TO PUBLIC;

//FOR DROPPING A DATABASE : DROP DATABASE DEMODATABASE;

CREATE OR REPLACE TABLE EDUCATION(
S_NO INT,
NAME STRING,
CLASS INT,
SECTION VARCHAR(5),
SCHOOL VARCHAR (27),
LOCATION VARCHAR(20),
PINCODE VARCHAR(10)  
);

INSERT INTO EDUCATION 
VALUES
(1,'NITISH',5,'A','SPACE CENTRAL SCHOOL','SULLURPETA',524121),
(2,'RAJESH',5,'A','SPACE CENTRAL SCHOOL','SULLURPETA',524121),
(3,'ANISH',5,'A','SPACE CENTRAL SCHOOL','SULLURPETA',524121),
(4,'MANOJ',5,'A','SPACE CENTRAL SCHOOL','SULLURETA',524121);
INSERT INTO EDUCATION(NAME,CLASS,PINCODE)
VALUES('RAM',5,524121);

DESCRIBE TABLE EDUCATION;
SELECT * FROM EDUCATION;

//HOW TO CREATE SCHEMAS

//METHOD1

CREATE SCHEMA HELLO;
USE SCHEMA HELLO;

CREATE OR REPLACE TABLE STUDENT_DETAILS(

  S_NO INT,
  NAME STRING,
  AGE INT
);


//METHOD 2

CREATE SCHEMA SCHOOL;

CREATE OR REPLACE TABLE SCHOOL.LECTURE_DETAILS(

  S_NO INT,
  NAME STRING,
  AGE INT
);






